# -----------------------------------------------------------------------------
# Email (Postmark || Any SMTP Provider)
# -----------------------------------------------------------------------------
SMTP_HOST="smtp.gmail.com"
SMTP_PORT="587"
SMTP_USER="username@hostname.com"
SMTP_PASS="some random password"
SMTP_FROM="username@hostname.com"

# -----------------------------------------------------------------------------
#  Reset Password 
# -----------------------------------------------------------------------------
RESET_PASSWORD_URL= "http://localhost:3000/resetpassword"
SECRET_KEY = "zen"
